
DATA_DIR: '/global/scratch/users/stanleychmwong/datasets/aorta_datasets/vmr_aorta_ct_dataset/'
# DATA_DIR: '/global/scratch/users/numi/ASOCA/'

# '/global/scratch/users/numi/vascular_data_3d/'
# '/Users/numisveins/Documents/ASOCA_dataset/', MICCAI_AVT_Data
# DATA_DIR: '/Users/numisveins/Documents/vascular_data_3d/' #, MICCAI_AVT_Data

DATASET_NAME: 'vmr' #'vmr' # or other 'other'

TESTING: False
MODALITY: ['CT'] # can also be 'MR' 'CT' or ['CT','MR'] if both
IMG_EXT: '.mha'

BINARIZE: True
ANATOMY: ['Aorta'] # can be 'ALL' or ['Aorta', 'Abdominal Aorta', 'Pulmonary', 'Coronary', 'CHD', 'Cerebro']
OUTLET_CLASSES: [0,1,2,3,4,5,6,7,8,9,10]
VALIDATION_PROP: 0.0 # 0.15
SCALED: False
CROPPED: False

EXTRACT_VOLUMES: True
ROTATE_VOLUMES: False

RESAMPLE_VOLUMES: False
RESAMPLE_SIZE: [64, 64, 64]

AUGMENT_VOLUMES: False

WRITE_SAMPLES: True
WRITE_IMG: True
REMOVE_OTHER: False # Remove other unconnected vessels in gt volume, can cause problems where vessels are close
WRITE_SURFACE: False
WRITE_CENTERLINE: False
WRITE_VOXEL_PYRAMID: False

WRITE_DISCRETE_CENTERLINE: False
DISCRETE_CENTERLINE_N_POINTS: 10

WRITE_OUTLET_STATS: False
WRITE_OUTLET_IMG: False
UPSAMPLE_OUTLET_IMG: False

WRITE_CROSS_SECTIONAL: False
WRITE_TRAJECTORIES: False

WRITE_VTK: True
WRITE_VTK_THROWOUT: False

MOVE_DIST: 1 # 1.5 how far to move along centerline between sampling, in terms of radius
SIZE_RADIUS: 5 # how big a volume to sample, x radius at each location
RADIUS_ADD: 0 # how much to add to radius values (to correct bias)
RADIUS_SCALE: 0 # how much to add to radius values (to correct bias)

CAPFREE: False # whether to require a certain amount of cap-free volume
CAPFREE_PROP: 0.0 # how much of volume must be cap free, per sidelength
MOVE_SLOWER_LARGE: 0.5  #0.5 how much slower for bigger vessels
MU_SIZE: 5 # mean for subvolume-radius ratio
SIGMA_SIZE: 0.8 # standard deviation for subvolume-radius ratio
MU_SHIFT: 0 # mean for subvolume shift off centerline
SIGMA_SHIFT: 0.8 # standard deviation for subvolume shift off centerline
NUMBER_SAMPLES: 5 # 2 how many samples to take at each point along vessel
NUMBER_SAMPLES_BIFURC: 7 # 3 how many samples to take if it's a bifurcation
NUMBER_SAMPLES_START: 5 # 5 how many samples to take at start of vessel (first 5%), better for initialization + bifurcations if not processed
MOVE_SLOWER_BIFURC: 0.5 # 0.1 how much slower for bigger vessels

MAX_SAMPLES: 100000

# Which cases to use for testing
TEST_CASES:
  #aortaseg24 aortas
  - 'subject045'
  - 'subject004'
  - 'subject003'
  - 'subject020'
  - 'subject028'
  - 'subject031'
  - 'subject042'
  - 'subject049'
  - 'subject025'
  - 'subject044'

  #miccai aortas
  - 'R9'
  - 'D8'
  - 'K3'
  - 'R17'
  - 'K8'
  - 'D12' 
  - 'R12' 
  - 'D6'

  #vmr
  - '0092_0001'
  - 'O20719_2006_aorta'
  - 'O128301_2008_aorta'
  - 'O227241_2006_aorta'
  - '0176_0000'
  - '0184_0001_aorta'
  - 'O0171SC_aorta'
  - 'O351095_2016_aorta'


# Which cases not to use in extraction
BAD_CASES:
  - '0092_0001' # Aorta with weird dimensions
  - '0064_1001' # Aorta with additional vessels
  - '0065_1001' # Aorta with additional vessels
  - '0140_2001' #AortofemoralCT
  - '0078_0001' #CerebroMR
  - '0079_0001' #CerebroMR
  - '0166_0001' #CerebroMR
  - '0167_0001' #CerebroMR

  